sudo: false
before_install:
  - brew update
  - brew install nvm
  - nvm install 0.12.7
script:
  - npm test
  - npm run release
os:
  - osx
notifications:
  email:
    on_success: never
    on_failure: change
